### ISSUE TITLE
Question about eeerotate

### ISSUE THREAD

**Issue by capsudo** [vkedwardli/TelegramChatHistoryImporter#2]
Sorry to create an issue for this but I found no other way to reach you.
I would like to know if you have a copy of eeerotate.exe available? The [project page](http://sites.google.com/site/vkedwardli/eeerotate) is dead.

**Comment by vkedwardli** [comment]
I'm not sure if it is still useful nowadays...

https://web.archive.org/web/20201101104233if_/https://9b30ce81-a-62cb3a1a-s-sites.googlegroups.com/site/vkedwardli/EeeRotate.v1.1.exe?attachauth=ANoY7cqduEoQHIVyOL8VmgSqP0PwYg8iN_d1blqqCCG715gSZ5HUf1_SApRrDqL03zEjs2qs9iw_PDWJmatY-w76SU6P-DQ1RrKZPvyhkllX8gbXaqVgHfWFVJXBn-t_3ziMK6gUYoJsmjcwl-n-RWueW4VEwjKdPiWHsBy7O9EE0lJMSHiexRbI_qT2gUm1paQmIXj3Gb1eAfJQGvyyyqyWsbArdxElQw%3D%3D&attredirects=0

**Comment by capsudo** [comment]
Thank you very much @vkedwardli! Yes it still works on windows 11
